- type: job
  id: Captain
  name: job-name-captain
  description: job-description-captain
  playTimeTracker: JobCaptain
  requirements:
    - !type:DepartmentTimeRequirement
      department: Engineering
      time: 36000 #10 hr
    - !type:DepartmentTimeRequirement
      department: Medical
      time: 36000 #10 hr
    - !type:DepartmentTimeRequirement
      department: Security
      time: 36000 #10 hr
#    - !type:DepartmentTimeRequirement
#      department: Command
#      time: 18000 # 5 hr
    - !type:OverallPlaytimeRequirement
      time: 72000 #20 hr
    - !type:AgeRequirement
      requiredAge: 21
  weight: 20
  startingGear: CaptainGear
  icon: "JobIconCaptain"
  requireAdminNotify: true
  joinNotifyCrew: true
  supervisors: job-supervisors-centcom
  canBeAntag: false
  accessGroups:
  - AllAccess
  #start-backmen: currency
  minBankBalance: 400
  maxBankBalance: 600
  wageDepartment: Command
  wage: 100
  #end-backmen: currency
  special:
  - !type:AddComponentSpecial
    components:
      - type: PsionicBonusChance
        flatBonus: 0.025
      - type: NpcFactionMember
        factions:
          - CentralCommand
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  - !type:AddComponentSpecial
    components:
      - type: CommandStaff

- type: startingGear
  id: CaptainGear
  equipment:
    shoes: ClothingShoesBootsLaceup
    eyes: ClothingEyesGlassesSunglasses
    gloves: ClothingHandsGlovesCaptain
    id: CaptainPDA
    ears: ClothingHeadsetAltCommand
  storage:
    back:
    - Flash
    # - StationCharter
